# Generated by Django 4.1.7 on 2023-03-22 11:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import van.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('work_requested', models.TextField()),
                ('work_progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tracking_id', models.UUIDField(default=uuid.uuid4)),
                ('finish', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Work_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_progress_done', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van.van')),
            ],
        ),
        migrations.CreateModel(
            name='Img_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=van.models.Img_tracking.path_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van.van')),
                ('work_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van.work_tracking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
