# Generated by Django 4.1.7 on 2023-03-21 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_tracking',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='van',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
