# Generated by Django 4.1.7 on 2023-03-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='van',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='work_tracking',
            old_name='van_id',
            new_name='van',
        ),
    ]
