# Generated by Django 4.1.7 on 2023-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0002_remove_work_tracking_tracking_id_van_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_tracking',
            name='finish',
        ),
        migrations.AddField(
            model_name='van',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
