# Generated by Django 4.1.7 on 2023-03-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0002_remove_img_tracking_work_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img_tracking',
            options={},
        ),
        migrations.RemoveField(
            model_name='van',
            name='work_requested',
        ),
        migrations.CreateModel(
            name='Work_requested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_request', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van.van')),
            ],
        ),
    ]
